name: Deploy On Development

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Configure PHP 8.1
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, yaml
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          check-latest: true
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 5

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVELOPMENT_HOST }}
          username: ${{ secrets.DEVELOPMENT_USERNAME }}
          port: ${{ secrets.DEVELOPMENT_PORT }}
          password: ${{ secrets.DEVELOPMENT_PASSWORD }}
          script: "cd /var/www/togoactive && ./.scripts/deploy.sh"
